=== deanem/deanem.github.io/resources/cineplex_concept/cineplex.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cinema (movie+) >
<!ELEMENT movie (movie_title, release_date?, runtime, poster_img, trailer, storyline, synopsis, director*, writers*, genre*, cast*, rating, official_website?, showtimes) >
<!ELEMENT movie_title (#PCDATA)>
<!ATTLIST movie_title certificate (u|pg|12|12a|15|18) #REQUIRED >
<!ELEMENT release_date (#PCDATA)>
<!ELEMENT runtime (#PCDATA)>
<!ELEMENT poster_img (#PCDATA)>
<!ELEMENT trailer (#PCDATA)>
<!ELEMENT storyline (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT writers (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT cast (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT official_website (#PCDATA)>
<!ELEMENT showtimes (date+)>
<!ELEMENT date (day, time+)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT time (#PCDATA)>

=== deanem/deanem.github.io/resources/cineplex_concept/cineplex.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cinema SYSTEM "http://b6bcineplex.alicoleman.com/cineplex.dtd">
<?xml-stylesheet type="text/xsl" href="cineplex.xsl"?>

<cinema>

	<movie>
		<movie_title certificate="15">21 Jump Street</movie_title>
		<release_date>March 16 2012</release_date>
		<runtime>110</runtime>
		<poster_img>21_jump_street</poster_img>
		<trailer>5k0mo_oJfn4</trailer>
		<storyline>A pair of underachieving cops are sent back to a local high school to blend in and bring down a synthetic drug ring.</storyline>
		<synopsis>In the action-comedy 21 Jump Street, Schmidt (Jonah Hill) and Jenko (Channing Tatum) are more than ready to leave their adolescent problems behind. Joining the police force and the secret Jump Street unit, they use their youthful appearances to go undercover in a local high school. As they trade in their guns and badges for backpacks, Schmidt and Jenko risk their lives to investigate a violent and dangerous drug ring. But they find that high school is nothing like they left it just a few years earlier - and neither expects that they will have to confront the terror and anxiety of being a teenager again and all the issues they thought they had left behind.</synopsis>
		<director>Phil Lord</director>
		<director>Christopher Miller</director>
		<writers>Jonah Hill</writers>
		<writers>Michael Bacall</writers>
		<genre>Action</genre>
		<genre>Comedy</genre>
		<cast>Jonah Hill</cast>
		<cast>Channing Tatum</cast>
		<cast>Brie Larson</cast>
		<rating>4.5</rating>
		<official_website>http://www.21jumpstreet-movie.com/</official_website>
		<showtimes>
			<date>
				<day>mon</day>
				<time>14:50</time>
				<time>17:30</time>
			</date>
			<date>
				<day>tue</day>
				<time>12:15</time>
				<time>14:50</time>
				<time>20:45</time>
			</date>
			<date>
				<day>wed</day>
				<time>12:15</time>
				<time>14:50</time>
				<time>20:45</time>
			</date>
			<date>
				<day>thur</day>
				<time>12:15</time>
				<time>14:50</time>
				<time>20:45</time>
			</date>
			<date>
				<day>fri</day>
				<time>15:40</time>
				<time>17:25</time>
				<time>19:30</time>
			</date>
			<date>
				<day>sat</day>
				<time>12:15</time>
				<time>14:50</time>
				<time>17:00</time>
				<time>20:45</time>
			</date>
			<date>
				<day>sun</day>
				<time>13:10</time>
				<time>15:40</time>
				<time>17:25</time>
				<time>19:30</time>
			</date>
		</showtimes>
	</movie>
	
	
	<movie>
		<movie_title certificate="12a">John Carter</movie_title>
		<release_date>March 9 2012</release_date>
		<runtime>132</runtime>
		<poster_img>john_carter</poster_img>
		<trailer>6Rf55GTEZ_E</trailer>
		<storyline>Transplanted to Mars, a Civil War vet discovers a lush planet inhabited by 12-foot tall barbarians. Finding himself a prisoner of these creatures, he escapes, only to encounter a princess who is in desperate need of a savior.</storyline>
		<synopsis>From Academy Award(R)-winning filmmaker Andrew Stanton comes John Carter sweeping action-adventure set on the mysterious and exotic planet of Barsoom (Mars). John Carter is based on a classic novel by Edgar Rice Burroughs, whose highly imaginative adventures served as inspiration for many filmmakers, both past and present.
The film tells the story of war-weary, former military captain John Carter (Taylor Kitsch), who is inexplicably transported to Mars where he becomes reluctantly embroiled in a conflict of epic proportions amongst the inhabitants of the planet, including Tars Tarkas (Willem Dafoe) and the captivating Princess Dejah Thoris (Lynn Collins). In a world on the brink of collapse, Carter rediscovers his humanity when he realizes that the survival of Barsoom and its people rests in his hands.</synopsis>
		<director>Andrew Stanton</director>
		<writers>Andrew Stanton</writers>
		<writers>Mark Andrews</writers>
		<writers>Michael Chabon</writers>
		<writers>Edgar Rice Burroughs</writers>
		<genre>Action</genre>
		<genre>Adventure</genre>
		<genre>Fantasy</genre>
		<cast>Taylor Kitsch</cast>
		<cast>Lynn Collins</cast>
		<cast>Willem Dafoe</cast>
		<rating>3.5</rating>
		<official_website>http://disney.go.com/johncarter/?cmp=wdsmp_jcm_url_johncarterarrives</official_website>
		<showtimes>
			<date>
				<day>mon</day>
				<time>16:30</time>
			</date>
			<date>
				<day>tue</day>
				<time>16:30</time>
			</date>
			<date>
				<day>wed</day>
				<time>16:30</time>
			</date>
			<date>
				<day>thur</day>
				<time>16:30</time>
			</date>
			<date>
				<day>fri</day>
				<time>15:20</time>
				<time>16:45</time>
				<time>19:40</time>
			</date>
			<date>
				<day>sat</day>
				<time>11:30</time>
				<time>16:30</time>
			</date>
			<date>
				<day>sun</day>
				<time>13:45</time>
				<time>19:45</time>
				<time>21:30</time>
			</date>
		</showtimes>
	</movie>
	
	<movie>
		<movie_title certificate="15">Safe House</movie_title>
		<release_date>FEB 24 2012</release_date>
		<runtime>115</runtime>
		<poster_img>safe_house</poster_img>
		<trailer>oWzTOoOpFa8</trailer>
		<storyline>A young CIA agent is tasked with looking after a fugitive in a safe house. But when the safe house is attacked, he finds himself on the run with his charge.</storyline>
		<synopsis>Oscar winner Denzel Washington and Ryan Reynolds star in the action-thriller Safe House. Washington plays the most dangerous renegade from the CIA, who comes back onto the grid after a decade on the run. When the South African safe house he's remanded to is attacked by mercenaries, a rookie operative (Reynolds) escapes with him. Now, the unlikely allies must stay alive long enough to uncover who wants them dead. For the past year, Matt Weston has been frustrated by his inactive, backwater post in Cape Town.
A housekeeper who aspires to be a full-fledged agent, the loyal company man has been waiting for an opportunity to prove himself. When the first and only occupant he's had proves to be the most dangerous man he's ever met, Weston readies for duty.
Tobin Frost has eluded capture for almost a decade. One of the best ops men that the CIA's known, the ex-intelligence officer has given up assets and sold military intel to anyone with cash since he turned. From trading secrets to North Korea to aiding splinter cells, the damage he's done to the U.S. is immeasurable. And he's now back on the reservation with a secret.
As soon as Frost is brought in for debriefing, mercenaries come and tear apart Weston's safe house. Barely escaping, the unlikely partners must discover if their attackers have been sent by terrorists or someone on the inside who will kill anyone standing in the way. Now it's up to Weston to figure out who he can trust before they're both eliminated from the game.</synopsis>
		<director>Daniel Espinosa</director>
		<writers>David Guggenheim</writers>
		<genre>Action</genre>
		<genre>Crime</genre>
		<genre>Mystery</genre>
		<cast>Denzel Washington</cast>
		<cast>Ryan Reynolds</cast>
		<cast>Brendan Gleeson</cast>
		<rating>3.5</rating>
		<official_website>http://www.nooneissafe.com/</official_website>
		<showtimes>
			<date>
				<day>mon</day>
				<time>16:20</time>
				<time>21:30</time>
			</date>
			<date>
				<day>tue</day>
				<time>16:20</time>
				<time>21:30</time>
			</date>
			<date>
				<day>wed</day>
				<time>16:20</time>
				<time>21:30</time>
			</date>
			<date>
				<day>thur</day>
				<time>16:20</time>
				<time>21:30</time>
			</date>
			<date>
				<day>fri</day>
				<time>13:40</time>
				<time>16:20</time>
				<time>21:30</time>
			</date>
			<date>
				<day>sat</day>
				<time>11:10</time>
				<time>16:20</time>
				<time>21:30</time>
			</date>
			<date>
				<day>sun</day>
				<time>11:10</time>
				<time>16:20</time>
				<time>21:30</time>
			</date>
		</showtimes>
	</movie>
	
	<movie>
		<movie_title certificate="u">The Muppets</movie_title>
		<release_date>FEB 10 2012</release_date>
		<runtime>110</runtime>
		<poster_img>the_muppets</poster_img>
		<trailer>C4YhbpuGdwQ</trailer>
		<storyline>With the help of three fans, The Muppets must reunite to save their old theater from a greedy oil tycoon.</storyline>
		<synopsis>On vacation in Los Angeles, Walter, the world's biggest Muppet fan, and his friends Gary (Jason Segel) and Mary (Amy Adams) from Smalltown, USA, discover the nefarious plan of oilman Tex Richman (Chris Cooper) to raze the Muppet Theater and drill for the oil recently discovered beneath the Muppets former stomping grounds.
To stage The Greatest Muppet Telethon Ever and raise the $10 million needed to save the theater, Walter, Mary and Gary help Kermit reunite the Muppets, who have all gone their separate ways: Fozzie now performs with a Reno casino tribute band called the Moppets, Miss Piggy is a plus-size fashion editor at Vogue Paris, Animal is in a Santa Barbara clinic for anger management, and Gonzo is a high-powered plumbing magnate.</synopsis>
		<director>James Bobin</director>
		<writers>Jason Segel</writers>
		<writers>Nicholas Stoller</writers>
		<genre>Comedy</genre>
		<cast>Jason Segel</cast>
		<cast>Amy Adams</cast>
		<cast>Chris Cooper</cast>
		<rating>3.5</rating>
		<official_website>http://www.disney.co.uk/muppets/</official_website>
		<showtimes>
			<date>
				<day>fri</day>
				<time>17:00</time>
				<time>19:30</time>
			</date>
			<date>
				<day>sat</day>
				<time>11:15</time>
			</date>
			<date>
				<day>sun</day>
				<time>11:15</time>
			</date>
		</showtimes>
	</movie>
	
	<movie>
		<movie_title certificate="12a">The Woman In Black</movie_title>
		<release_date>FEB 10 2012</release_date>
		<runtime>95</runtime>
		<poster_img>the_woman_in_black</poster_img>
		<trailer>dPYMUnJGURI</trailer>
		<storyline>A young lawyer travels to a remote village where he discovers the vengeful ghost of a scorned woman is terrorizing the locals.</storyline>
